version: '3'

services:

######################################################
# PROJECT EXAMPLE CONTAINER
######################################################
  mlpanel-example-2:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: mlpanel/mlpanel-example-2-local-project:latest
    network_mode: 'mlpanel_default'
    env_file:
      - .env
    environment:
      PYTHONPATH: '/home/mlpanel-example-2'
      PROJECT_PATH: '/home/mlpanel-example-2'
      LANG: 'C.UTF-8'
      JUPYTER_ENABLE_LAB: 'yes'
    ports:
      - 8888:8888
    volumes:
      - ./:/home/mlpanel-example-2
      - $WORKSPACE:$WORKSPACE